/* Generated By:JJTree: Do not edit this line. ASTLiteral.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef JAVACC_ASTLiteral_H
#define JAVACC_ASTLiteral_H

#include "Node.h"


class ASTLiteral : public Node {
public: 
  ASTLiteral(int id);
  virtual ~ASTLiteral();

  /** Accept the visitor. **/
  virtual void jjtAccept(EcmaScriptVisitor *visitor, void * data) const ;
  
 void setDecimalValue(const JJString& s);
 void setHexValue(const JJString& s);
 void setStringValue(const JJString& s);
 void setBooleanValue(const JJString& s);
 void setNullValue();
 void setRegexValue(const JJString& s);
 
 private:
  JJString value;
};


#endif
/* JavaCC - OriginalChecksum=d2a24b1fc4e45108624c0b9ccf44904e (do not edit this line) */
