/* Generated By:JJTree: Do not edit this line. ASTAssignment.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTAssignment : public Node {
public: 
  ASTAssignment(int id);
  virtual ~ASTAssignment();
  virtual void interpret();
};

/* JavaCC - OriginalChecksum=48cfba6a3e9cb319de83e009c63b63e9 (do not edit this line) */
