/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseXorNode.h"

  
  ASTBitwiseXorNode::ASTBitwiseXorNode(int id) : Node(id) {
  }
  ASTBitwiseXorNode::~ASTBitwiseXorNode() {
  }


/* JavaCC - OriginalChecksum=19e431f19121e3eddcaaf528d501a1ed (do not edit this line) */
