/* Generated By:JJTree: Do not edit this line. ASTBlock.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBlock.h"

  
  ASTBlock::ASTBlock(int id) : Node(id) {
  }
  ASTBlock::~ASTBlock() {
  }


/* JavaCC - OriginalChecksum=83baaa94a250388acb7e7f1a56f03806 (do not edit this line) */
