/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTCompilationUnit.h"

  
  ASTCompilationUnit::ASTCompilationUnit(int id) : Node(id) {
  }
  ASTCompilationUnit::~ASTCompilationUnit() {
  }


/* JavaCC - OriginalChecksum=3832884a1651f39b7beec8c4cf7e7d4d (do not edit this line) */
