/* Generated By:JJTree: Do not edit this line. ASTEQNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTEQNode : public Node {
public: 
  ASTEQNode(int id);
  virtual ~ASTEQNode();

};

/* JavaCC - OriginalChecksum=4093cfca9a86d05e41aee90376198422 (do not edit this line) */
