/* Generated By:JJTree: Do not edit this line. ASTEQNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTEQNode.h"

  
  ASTEQNode::ASTEQNode(int id) : Node(id) {
  }
  ASTEQNode::~ASTEQNode() {
  }


/* JavaCC - OriginalChecksum=b9d040f0efe5f4a180c93ca72c73b21f (do not edit this line) */
