/* Generated By:JJTree: Do not edit this line. ASTFalseNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTFalseNode : public Node {
public: 
  ASTFalseNode(int id);
  virtual ~ASTFalseNode();

};

/* JavaCC - OriginalChecksum=c7fab00a1855468ace70e6b2470fd3b2 (do not edit this line) */
