/* Generated By:JJTree: Do not edit this line. ASTGENode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTGENode : public Node {
public: 
  ASTGENode(int id);
  virtual ~ASTGENode();

};

/* JavaCC - OriginalChecksum=6a0c92f95bd202c09305400a6d1f2541 (do not edit this line) */
