/* Generated By:JJTree: Do not edit this line. ASTGENode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTGENode.h"

  
  ASTGENode::ASTGENode(int id) : Node(id) {
  }
  ASTGENode::~ASTGENode() {
  }


/* JavaCC - OriginalChecksum=748c6f115744e891d2713b8f50347b12 (do not edit this line) */
