/* Generated By:JJTree: Do not edit this line. ASTIfStatement.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTIfStatement : public Node {
public: 
  ASTIfStatement(int id);
  virtual ~ASTIfStatement();

};

/* JavaCC - OriginalChecksum=a389980a7492a96d4ee1d322dc8262b1 (do not edit this line) */
