/* Generated By:JJTree: Do not edit this line. ASTIfStatement.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTIfStatement.h"

  
  ASTIfStatement::ASTIfStatement(int id) : Node(id) {
  }
  ASTIfStatement::~ASTIfStatement() {
  }


/* JavaCC - OriginalChecksum=792dfac6bb69d54a99ca4f1d5adf2cd2 (do not edit this line) */
