/* Generated By:JJTree: Do not edit this line. ASTLTNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTLTNode : public Node {
public: 
  ASTLTNode(int id);
  virtual ~ASTLTNode();

};

/* JavaCC - OriginalChecksum=cff308cfe5545681d4d2920e556b2ab8 (do not edit this line) */
