/* Generated By:JJTree: Do not edit this line. ASTMulNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTMulNode : public Node {
public: 
  ASTMulNode(int id);
  virtual ~ASTMulNode();

};

/* JavaCC - OriginalChecksum=98fe24aa351aea0c0891a7b1e16c8a5a (do not edit this line) */
