/* Generated By:JJTree: Do not edit this line. ASTNotNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTNotNode : public Node {
public: 
  ASTNotNode(int id);
  virtual ~ASTNotNode();

};

/* JavaCC - OriginalChecksum=942374887d33ad848cf1c8ecafbaf041 (do not edit this line) */
