/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTSubtractNode.h"

  
  ASTSubtractNode::ASTSubtractNode(int id) : Node(id) {
  }
  ASTSubtractNode::~ASTSubtractNode() {
  }


/* JavaCC - OriginalChecksum=5d9fad3656acacee54656bf201436e5b (do not edit this line) */
