/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTSubtractNode : public Node {
public: 
  ASTSubtractNode(int id);
  virtual ~ASTSubtractNode();

};

/* JavaCC - OriginalChecksum=1130f20c5e3d0528ba18ccbcf3979cc4 (do not edit this line) */
