/* Generated By:JJTree: Do not edit this line. ASTTrueNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTTrueNode.h"

  
  ASTTrueNode::ASTTrueNode(int id) : Node(id) {
  }
  ASTTrueNode::~ASTTrueNode() {
  }


/* JavaCC - OriginalChecksum=ccbedb408904f88f24bcd3e2aeb24f88 (do not edit this line) */
