/* Generated By:JJTree: Do not edit this line. ASTTrueNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTTrueNode : public Node {
public: 
  ASTTrueNode(int id);
  virtual ~ASTTrueNode();

};

/* JavaCC - OriginalChecksum=596701d03cb5065b8427d1a044c30c52 (do not edit this line) */
