/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTVarDeclaration.h"
#include "Boolean.h"
#include "Integer.h"
#include "SPLParserConstants.h"

  
  ASTVarDeclaration::ASTVarDeclaration(int id) : Node(id) {
  }
  ASTVarDeclaration::~ASTVarDeclaration() {
  }
  void ASTVarDeclaration::interpret()
  {
     if (type == BOOL)
        symtab[name] =  new Boolean(false);
     else
		symtab[name] = new Integer(0);
  }
/* JavaCC - OriginalChecksum=f114702c2f87d4e2a181c474eeb058f9 (do not edit this line) */
