/* Generated By:JJTree: Do not edit this line. ASTIdentifier.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTIdentifier.h"
#include "EcmaScriptVisitor.h"

  
  ASTIdentifier::ASTIdentifier(int id) : Node(id) {
  }
  ASTIdentifier::~ASTIdentifier() {
  }

  /** Accept the visitor. **/
  void ASTIdentifier::jjtAccept(EcmaScriptVisitor *visitor, void * data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=1373f6fe63e12d920a432e21f3dc6d75 (do not edit this line) */
