/* Generated By:JJTree: Do not edit this line. ASTAndNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTAndNode : public Node {
public: 
  ASTAndNode(int id);
  virtual ~ASTAndNode();
  virtual void interpret();
};

/* JavaCC - OriginalChecksum=6b8e29e56db28d832c4478bb8d1eae54 (do not edit this line) */
