/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseOrNode.h"

  
  ASTBitwiseOrNode::ASTBitwiseOrNode(int id) : Node(id) {
  }
  ASTBitwiseOrNode::~ASTBitwiseOrNode() {
  }


/* JavaCC - OriginalChecksum=bffc2111189f5959c645ab085f46895b (do not edit this line) */
