/* Generated By:JJTree: Do not edit this line. ASTBlock.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTBlock : public Node {
public: 
  ASTBlock(int id);
  virtual ~ASTBlock();

};

/* JavaCC - OriginalChecksum=e5ff3b72a4fe6c2cf80f3cb127c5ac9f (do not edit this line) */
