/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTBitwiseOrNode : public Node {
public: 
  ASTBitwiseOrNode(int id);
  virtual ~ASTBitwiseOrNode();

};

/* JavaCC - OriginalChecksum=8e706ab7df4d50fadc04d8e2748a109e (do not edit this line) */
