/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTBitwiseXorNode : public Node {
public: 
  ASTBitwiseXorNode(int id);
  virtual ~ASTBitwiseXorNode();

};

/* JavaCC - OriginalChecksum=8b15cddc6a6953533093a085938a4fa3 (do not edit this line) */
