/* Generated By:JJTree: Do not edit this line. ASTFalseNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTFalseNode.h"

  
  ASTFalseNode::ASTFalseNode(int id) : Node(id) {
  }
  ASTFalseNode::~ASTFalseNode() {
  }


/* JavaCC - OriginalChecksum=772ca8ec3d3b7778622a392c73938e50 (do not edit this line) */
