/* Generated By:JJTree: Do not edit this line. ASTGTNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTGTNode : public Node {
public: 
  ASTGTNode(int id);
  virtual ~ASTGTNode();

};

/* JavaCC - OriginalChecksum=71ba6254c1f304c164d485a5207f827c (do not edit this line) */
