/* Generated By:JJTree: Do not edit this line. ASTLTNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTLTNode.h"

  
  ASTLTNode::ASTLTNode(int id) : Node(id) {
  }
  ASTLTNode::~ASTLTNode() {
  }


/* JavaCC - OriginalChecksum=5434a107f33ae026cc0744d46ddb18b7 (do not edit this line) */
