/* Generated By:JJTree: Do not edit this line. ASTNENode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTNENode : public Node {
public: 
  ASTNENode(int id);
  virtual ~ASTNENode();

};

/* JavaCC - OriginalChecksum=9d045612143a1a2564a2db5945b8420d (do not edit this line) */
