/* Generated By:JJTree: Do not edit this line. ASTNotNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTNotNode.h"

  
  ASTNotNode::ASTNotNode(int id) : Node(id) {
  }
  ASTNotNode::~ASTNotNode() {
  }


/* JavaCC - OriginalChecksum=497b5da418ef3d48d07c15ce07249f3d (do not edit this line) */
