/* Generated By:JJTree: Do not edit this line. ASTOrNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTOrNode : public Node {
public: 
  ASTOrNode(int id);
  virtual ~ASTOrNode();

};

/* JavaCC - OriginalChecksum=0e1bd6caeeac08a9fdab2066a325f4ab (do not edit this line) */
