/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTStatementExpression : public Node {
public: 
  ASTStatementExpression(int id);
  virtual ~ASTStatementExpression();

};

/* JavaCC - OriginalChecksum=033cf485f944e8cd864cf74698a16e32 (do not edit this line) */
