int main(int argc, char** argv) {
	return 0;
}
#if 0
import java.io.StringReader;

/**
 * A class partly generated by <a href="http://javacc.dev.java.net" target="_top">JavaCC</a> which translates
 * ancient greek style "prefixs" to an integer.
 *
 * Released under the LGPL by the University of Manchester 2003
 *
 * @author Stephen Tomkinson
 */

public class ChemNumber {
    private static int currentNumber;

    /**
     * Converts the ancient greek style "prefix" string into an int.
     *
     * @throws ParseException Any error which occur in the parsing get wrapped
     * up in a ParseException and thrown.
     */
    public static int fromString (String stringToParse) throws ParseException
    {
        currentNumber = 0;

        StringReader stringReader = new StringReader (stringToParse.toLowerCase() + "\n");
        ChemNumber parser = new ChemNumber (stringReader);               
        parser.wholeNumber();

        return currentNumber;
    }

    public static void main (String args[])
    {
        try
        {
            System.out.println ("Returned: " + fromString(args[0]));
        }
        catch (Throwable t)
        {
            System.out.println (t);
        }
    }
}
#endif