/* Generated By:JavaCC: Do not edit this line. MyToken.h Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true,INCLUDE_FOR_TOKEN=null,TOKEN_SUPER_CLASS= */
#ifndef JAVACC_MY_TOKEN_H
#define JAVACC_MY_TOKEN_H

#include "JavaCC.h"
#include "Token.h"


namespace FOO {
	namespace BAR {

		/**
		 * Describes the input token stream.
		 */

		class MyToken : public Token 
		{
		public:
			MyToken();
			MyToken(int kind);
			MyToken(int kind, const JJString& image);
			virtual ~MyToken();

		};

	}
}

#endif
/* JavaCC - OriginalChecksum=e3baa43daacdfb1726cde686d5d46cdd (do not edit this line) */
