/* Generated By:JavaCC: Do not edit this line. MyToken.cc Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true,INCLUDE_FOR_TOKEN=null,TOKEN_SUPER_CLASS= */
#include "MyToken.h"
namespace FOO {
	namespace BAR {
		MyToken::MyToken()
		{
		}

		MyToken::MyToken(int kind) : Token(kind)
		{
		}

		MyToken::MyToken(int kind, const JJString& image)  : Token(kind, image)
		{
		}

		MyToken::~MyToken() {
		}


	}
}
/* JavaCC - OriginalChecksum=9436fc46454be004c97bbc7e79c818d5 (do not edit this line) */
