/* Generated By:JavaCC: Do not edit this line. SpecialTokenConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGenCPP#start()
 */
#ifndef SPECIALTOKENCONSTANTS_H
#define SPECIALTOKENCONSTANTS_H
#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int NA = 9;
  /** RegularExpression Id. */
const  int EOL = 10;
  /** RegularExpression Id. */
const  int Id = 13;

  /** Lexical state. */
const  int DEFAULT = 0;
  /** Lexical state. */
const  int LinesComment = 1;
  /** Lexical state. */
const  int LineComment = 2;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0x2f, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x2f, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x2a, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_8[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x38, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_9[] = 
{0x22, 0x3c, 0x4e, 0x41, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_10[] = 
{0x22, 0x3c, 0x45, 0x4f, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_11[] = 
{0x22, 0x2d, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_12[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x31, 0x32, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_13[] = 
{0x22, 0x3c, 0x49, 0x64, 0x3e, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
  };

#endif
