/* Generated By:JJTree: Do not edit this line. ASTLiteral.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTLiteral.h"
#include "EcmaScriptVisitor.h"

  
  ASTLiteral::ASTLiteral(int id) : Node(id) {
  }
  ASTLiteral::~ASTLiteral() {
  }

  /** Accept the visitor. **/
  void ASTLiteral::jjtAccept(EcmaScriptVisitor *visitor, void * data) const {
    visitor->visit(this, data);
  }
  
 void  ASTLiteral::setDecimalValue(const JJString& s) {
 	value = s;
 }
 void  ASTLiteral::setHexValue(const JJString& s) {
 	value = s;
 }
 void  ASTLiteral::setStringValue(const JJString& s) {
 	value = s;
 }
 void  ASTLiteral::setBooleanValue(const JJString& s) {
 	value = s;
 }
 void  ASTLiteral::setNullValue()  {
 }
 void  ASTLiteral::setRegexValue(const JJString& s) {
 	value = s;
 }
  

/* JavaCC - OriginalChecksum=520f7516b1b762ba60a657255f7837a7 (do not edit this line) */
