/* Generated By:JJTree: Do not edit this line. ASTAddNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTAddNode : public Node {
public: 
  ASTAddNode(int id);
  virtual ~ASTAddNode();
  virtual void interpret();
};

/* JavaCC - OriginalChecksum=a0aedef5ef4e377dc9a0310d6ebabe28 (do not edit this line) */
