/* Generated By:JJTree: Do not edit this line. ASTAssignment.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTId.h"
#include "ASTAssignment.h"

  
  ASTAssignment::ASTAssignment(int id) : Node(id) {
  }
  ASTAssignment::~ASTAssignment() {
  }
  void ASTAssignment::interpret()
  {
     string name;

     jjtGetChild(1)->interpret();
	 //    symtab.put(name = ((ASTId)jjtGetChild(0)).name, stack[top]);
	 Node* top = stack.top();
	 name =  ((ASTId*)jjtGetChild(0))->name;
     symtab[name] = top;
  }


/* JavaCC - OriginalChecksum=9bf39c0f54281bb5120b3a65d9e51422 (do not edit this line) */
