/* Generated By:JJTree: Do not edit this line. ASTBitwiseComplNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseComplNode.h"
#include "Integer.h"

  
  ASTBitwiseComplNode::ASTBitwiseComplNode(int id) : Node(id) {
  }
  ASTBitwiseComplNode::~ASTBitwiseComplNode() {
  }
  void ASTBitwiseComplNode::interpret()
  {
     jjtGetChild(0)->interpret();

	 unique_ptr<Integer> top((Integer*)stack.top()); stack.pop();

     stack.push(new Integer(~(*top)));
  }


/* JavaCC - OriginalChecksum=375357417b50e290d42e38b5c6ba21a2 (do not edit this line) */
