/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTCompilationUnit : public Node {
public: 
  ASTCompilationUnit(int id);
  virtual ~ASTCompilationUnit();

};

/* JavaCC - OriginalChecksum=9647c468a98022aae70bd3ec6efd3f94 (do not edit this line) */
