/* Generated By:JJTree: Do not edit this line. ASTDivNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTDivNode.h"

  
  ASTDivNode::ASTDivNode(int id) : Node(id) {
  }
  ASTDivNode::~ASTDivNode() {
  }


/* JavaCC - OriginalChecksum=26ed2569eed2c98ef8ccfe9547870d1e (do not edit this line) */
