/* Generated By:JJTree: Do not edit this line. ASTDivNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"


class ASTDivNode : public SimpleNode {
public: 
  ASTDivNode(int id);
  virtual ~ASTDivNode();

};

/* JavaCC - OriginalChecksum=0a22c38ef433a330fa120239da323e5e (do not edit this line) */
