/* Generated By:JJTree: Do not edit this line. ASTGTNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTGTNode.h"

  
  ASTGTNode::ASTGTNode(int id) : Node(id) {
  }
  ASTGTNode::~ASTGTNode() {
  }


/* JavaCC - OriginalChecksum=7a457b603fc1bd56f096b970fbfb40df (do not edit this line) */
