/* Generated By:JJTree: Do not edit this line. ASTIntConstNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTIntConstNode.h"
#include "Integer.h"

  
  ASTIntConstNode::ASTIntConstNode(int id) : Node(id) {
  }
  ASTIntConstNode::~ASTIntConstNode() {
  }
  void ASTIntConstNode::interpret()
  {
     stack.push(new Integer(val));
  }

/* JavaCC - OriginalChecksum=d65eb251edf8825bf29bf1a875c34589 (do not edit this line) */
