/* Generated By:JJTree: Do not edit this line. ASTLENode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTLENode : public Node {
public: 
  ASTLENode(int id);
  virtual ~ASTLENode();

};

/* JavaCC - OriginalChecksum=bb2abdfe166b69d2d7d48e2e039117db (do not edit this line) */
