/* Generated By:JJTree: Do not edit this line. ASTLENode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTLENode.h"

  
  ASTLENode::ASTLENode(int id) : Node(id) {
  }
  ASTLENode::~ASTLENode() {
  }


/* JavaCC - OriginalChecksum=b762447a14233866b932ebc1419f9e76 (do not edit this line) */
