/* Generated By:JJTree: Do not edit this line. ASTModNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTModNode.h"

  
  ASTModNode::ASTModNode(int id) : Node(id) {
  }
  ASTModNode::~ASTModNode() {
  }


/* JavaCC - OriginalChecksum=d0251fcc1b0f5a4597acdd48e1ef2547 (do not edit this line) */
