/* Generated By:JJTree: Do not edit this line. ASTModNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"


class ASTModNode : public SimpleNode {
public: 
  ASTModNode(int id);
  virtual ~ASTModNode();

};

/* JavaCC - OriginalChecksum=a17f050f7a5e96e2f2a8b32b20b2a522 (do not edit this line) */
