/* Generated By:JJTree: Do not edit this line. ASTMulNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTMulNode.h"

  
  ASTMulNode::ASTMulNode(int id) : Node(id) {
  }
  ASTMulNode::~ASTMulNode() {
  }


/* JavaCC - OriginalChecksum=f7d82f2c2f5cf6bac2a3ecb0739c3f63 (do not edit this line) */
