/* Generated By:JJTree: Do not edit this line. ASTNENode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTNENode.h"

  
  ASTNENode::ASTNENode(int id) : Node(id) {
  }
  ASTNENode::~ASTNENode() {
  }


/* JavaCC - OriginalChecksum=978b90e60dbfb8eb14634ba25070cac5 (do not edit this line) */
