/* Generated By:JJTree: Do not edit this line. ASTOrNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTOrNode.h"

  
  ASTOrNode::ASTOrNode(int id) : Node(id) {
  }
  ASTOrNode::~ASTOrNode() {
  }


/* JavaCC - OriginalChecksum=a5cff3738073393004448a55c222732b (do not edit this line) */
