/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTStatementExpression.h"

  
  ASTStatementExpression::ASTStatementExpression(int id) : Node(id) {
  }
  ASTStatementExpression::~ASTStatementExpression() {
  }


/* JavaCC - OriginalChecksum=1cbf38c89ca29b7350158da38db24149 (do not edit this line) */
