/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTVarDeclaration : public Node {
public: 
  ASTVarDeclaration(int id);
  virtual ~ASTVarDeclaration();
  virtual void interpret();
  friend class SPLParser;
  
private:
  string name;
  int type;
};

/* JavaCC - OriginalChecksum=cc6d29a8c0f30f80ab8d6d92ab0fb673 (do not edit this line) */
