/* Generated By:JJTree: Do not edit this line. ASTWriteStatement.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTWriteStatement : public Node {
public: 
  ASTWriteStatement(int id);
  virtual ~ASTWriteStatement();
  virtual void interpret();
  friend class SPLParser;

private:
	string name;
};

/* JavaCC - OriginalChecksum=98dc637028c0987f86059ca34493f1a1 (do not edit this line) */
