/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class ASTWhileStatement : public Node {
public: 
  ASTWhileStatement(int id);
  virtual ~ASTWhileStatement();

};

/* JavaCC - OriginalChecksum=6eed428313d73e3dc20d77c1b427cd26 (do not edit this line) */
