/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTWhileStatement.h"

  
  ASTWhileStatement::ASTWhileStatement(int id) : Node(id) {
  }
  ASTWhileStatement::~ASTWhileStatement() {
  }


/* JavaCC - OriginalChecksum=06d7f403e03ef8a95546abea6c90a25d (do not edit this line) */
