# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8.git
         path: javacc-8
         ref: release
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-core.git
         path: javacc-8/core
         ref: release
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-cpp.git
         path: javacc-8/codegen/cpp
         ref: release
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-java.git
         path: javacc-8/codegen/java
         ref: release
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-csharp.git
         path: javacc-8/codegen/csharp
         ref: release
    - uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-js .git
         path: javacc-8/codegen/js
         ref: release
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean verify --file javacc-8/pom.xml
