# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]

    steps:
    - name: clone javacc-8
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8.git
         path: javacc-8
         ref: release
    - name: clone javacc-8-core
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-core.git
         path: javacc-8/core
         ref: release
    - name: clone javacc-8-cpp
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-cpp.git
         path: javacc-8/codegen/cpp
         ref: release
    - name: clone javacc-8-java
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-java.git
         path: javacc-8/codegen/java
         ref: release
    - name: clone javacc-8-csharp
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-csharp.git
         path: javacc-8/codegen/csharp
         ref: release
    - name: clone javacc-8-js
      uses: actions/checkout@v3
      with:
         repository: javacc/javacc-8-js.git
         path: javacc-8/codegen/js
         ref: release
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '8'
         cache: 'maven'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build org:javacc
      run: mvn -B -e clean install -N --file javacc-8/pom.xml

    - name: Build JavaCC core & generators
      run: mvn -B -e clean verify --file javacc-8/pom.xml
      